package com.interview.graphql.dto;

public record CreateApplicationInput(
        String companyName,
        String jobTitle,
        String jobUrl,
        String companyWebsite,
        String companyLinkedinUrl,
        String location,
        String status,
        String priority,
        String remoteType,
        String applicationMethod,
        String applicationMethodOther,
        Integer salaryMin,
        Integer salaryMax,
        String salaryCurrency,
        Boolean visaSponsorship,
        String taName,
        String taEmail,
        String taLinkedinUrl,
        String taPhone,
        String hiringManagerName,
        String hiringManagerLinkedinUrl,
        Boolean linkedinConnectionSent,
        Boolean linkedinMessageSent,
        String followUpDate,
        String lastContactDate,
        String responseReceivedAt,
        String interviewDate,
        String lastAppliedAt,
        String applicationSource,
        String linkedOfferId,
        String notes) {
}
